version: '3'

networks:
  jobsdotgoplus_net:

volumes:
  redis_data:

services:

  redis:
    image: ${APP_NAME}_redis:${APP_VERSION:-1.0}
    build:
      context: ./redis
      args:
        REDIS_DOCKER_VERSION: ${REDIS_DOCKER_VERSION}
    container_name: ${APP_NAME}_redis
    restart: ${RESTART_POLICY}
    volumes:
      - redis_data:/data
    networks:
      - jobsdotgoplus_net
    ports:
      - "${REDIS_PORT}:6379"


  php-apache:
    image: ${APP_NAME}_php-apache:${APP_VERSION:-1.0}
    build:
      context: ./php-apache
      args:
        PHP_DOCKER_VERSION: ${PHP_DOCKER_VERSION}
    container_name: ${APP_NAME}_php-apache
    restart: ${RESTART_POLICY}
    depends_on:
      - redis
    networks:
      - jobsdotgoplus_net
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ../src:/var/www/html/:rw
